### ISSUE TITLE
error while building OCL with CXX and PYTHON support

### ISSUE THREAD

**Issue by TurBoss** [aewallin/opencamlib#61]
hello I'm trying to build ocl in arch to use with blendercam

when runnning cmake it fails with the following error

http://dpaste.com/3FRYJ4J

thanks

**Comment by aewallin** [comment]
thanks for reporting, can you report your cmake version?
On ubuntu LTS it outputs:
$ cmake --version
cmake version 3.10.2

maybe you have a much newer cmake??

if you want to experiment, try outputting (e.g. MESSAGE) the value of ${OpenCamLib_SOURCE_DIR} in src/cxxlib/cxxlib.cmake
the error looks like it wrongly might point to the build-directory (not the source root dir)

**Comment by TurBoss** [comment]
MESSAGE(${OpenCamLib_SOURCE_DIR})
/home/turboss/Projects/opencamlib/src

**Comment by aewallin** [comment]
hm, ok.

I think this is because the same C++ is now configured to be compiled many times, for different targets.
The cmake config runs fine for the first target (line 46 in your pasted output) - but then for the second target cmake is configured to build the same source again, and there's an error because the directory is already being built.

the solution could be to build the C++ sources only once, and the bindings (python, java, whatever) would then link against the already built C++ library.

you could try configuring cmake NOT to build the C++ library, only the Python module - that might work...

**Comment by TurBoss** [comment]
disable cxx made cmake happy

but make does nothing
http://dpaste.com/19ZD6KK

thanks!

**Comment by aewallin** [comment]
only py2 lib seems to work over here:

> cmake -DBUILD_PY_LIB=ON -DBUILD_CXX_LIB=OFF -DUSE_PY_3=OFF ../src

make sure you clear the cmake cache between config changes.. (delete CMakeCache.txt)

**Comment by TurBoss** [comment]
nice 
compiled success
thank you so much

**Comment by vespakoen** [comment]
Ah yes, the cxx lib build is on by default (we should probably turn this off).
Or make sure when building multiple targets they play nice together.

**Comment by J-Dunn** [comment]
I don't have much experience of cmake but I don't see why this is a problem, in make you would just define the cxx files as a dep of py stuff , if it is upto date, it would not be rebuilt and there would not be an issue. 

Isn't this a  bug in the way the python build is defined?

**Comment by aewallin** [comment]
the cmake-build has grown a bit complex...

the pure c++ build should be kept as simple as possible and not touched much.
bindings should link against the pure c++ binary/headers and not build their own IMO.

the different bindings could probably go into separate directories with their own build-system so that they don't disturb to main c++ build.

not sure when/if I will have time to look at this - especially for platforms I don't work much on (win/mac) - so PRs are welcome..

**Comment by zachGummow** [comment]
I was able to build both CXX and Python simultaneously. I have my changes in this pull request: [#66](https://github.com/aewallin/opencamlib/pull/66)

**Comment by aewallin** [comment]
closing this for now - please open new issues with details if there are further build problems.
