### ISSUE TITLE
Installing on MacOS X

### ISSUE THREAD

**Issue by luzpaz** [aewallin/opencamlib#75]
There is no homebrew or macport available for opencamlib.  
ref: https://github.com/Schamschula/macports/issues/4

**Comment by zohozer** [comment]
I also need OCL for MacOS. How I can get a build for MacOS?

**Comment by aewallin** [comment]
I think the build altogether has gotten a bit complex. 
It would be good to revise the codebase and build so that a minimal library can be built only using a c++ compiler and the boost libraries.
all python etc. bindings could/should be optional.
this way supporting builds on many platforms should be easier.

**Comment by vejmarie** [comment]
I just updated opencad lib cmake to make it work with latest homebrew (PR #85). I will update homebrew formula later today. It shall be readily installable on catalina and from source

**Comment by vespakoen** [comment]
OpenCAMLib is now available on PyPi.

It can now be installed with pip:

```shell
pip install opencamlib
```

It looks like the FreeCAD OpenCAMLib formula does not build the Python library, and doesn't enable OpenMP. It should probably be updated.

https://github.com/FreeCAD/homebrew-freecad/blob/master/Formula/opencamlib.rb

I also just read that homebrew advices agains putting packages on homebrew that are already on PyPi (https://docs.brew.sh/Python-for-Formula-Authors).
So maybe we can get rid of it now?
